### ISSUE TITLE
`.only` in test suites are masking test failures

### ISSUE THREAD

**Issue by coopy** [nikgraf/belle#251]
These commits added [`it.only`](https://facebook.github.io/jest/docs/api.html#globally-injected-variables) statements:

https://github.com/nikgraf/belle/commit/8f590e27bf0da53828ff7d8fdac32d759e480aa5#diff-b463099e9ad97c8e208479a3563abc48R144

https://github.com/nikgraf/belle/commit/2dc5832e0312331b276143e46cbff032485bca41#diff-a950297569f3855e5b31a4abdf3530dbR202

These appear to be masking actual test failures. When those `it.only` statements are turned into `it` statements, there are multiple failures:

```
$ npm test

> belle@2.0.3 test [path]/belle
> BABEL_ENV=test BABEL_JEST_STAGE=0 jest src/

Using Jest CLI v0.8.2, jasmine1
 PASS  src/__tests__/helpers-test.js (2.856s)
 FAIL  src/__tests__/Button-test.js (2.544s)
● Button › it should be able to adopt the pseudoClass styles of the button
  - Expected: 'active' toBe: 'focus'
        at Spec.eval (src/__tests__/Button-test.js:127:35)
  - Expected: '#C5C4C4' toBe: 'brown'
        at Spec.eval (src/__tests__/Button-test.js:128:35)
● Button › without any properties › it should inject styles for active & foucs
  - Expected: 'active' toBe: 'focus'
        at Spec.eval (src/__tests__/Button-test.js:42:37)
 PASS  src/__tests__/ComboBox-test.js (6.641s)
 PASS  src/__tests__/Rating-test.js (1.802s)
 PASS  src/__tests__/TextInput-test.js (1.207s)
 PASS  src/__tests__/Separator-test.js (0.735s)
 PASS  src/__tests__/Placeholder-test.js (0.775s)
 PASS  src/__tests__/Card-test.js (0.752s)
 PASS  src/__tests__/Option-test.js (0.597s)
 PASS  src/__tests__/Select-test.js (9.735s)
 PASS  src/__tests__/Spinner-test.js (0.701s)
 PASS  src/__tests__/union-class-names-test.js (0.451s)
 FAIL  src/__tests__/DatePicker-test.js (13.995s)
● DatePicker › it should initialise props as expected
  - Expected: undefined toBe: 12
        at Spec.eval (src/__tests__/DatePicker-test.js:22:36)
  - Expected: undefined toBe: 2015
        at Spec.eval (src/__tests__/DatePicker-test.js:23:35)
● DatePicker › it should change date when a day is focused and enter key is pressed
  - TypeError: Cannot read property 'tagName' of undefined
        at Object.eval [as focus] (node_modules/react/lib/ReactTestUtils.js:381:34)
        at Spec.eval (src/__tests__/DatePicker-test.js:45:48)
● DatePicker › it should select / deselect date when space key is pressed
  - TypeError: Cannot read property 'tagName' of undefined
        at Object.eval [as focus] (node_modules/react/lib/ReactTestUtils.js:381:34)
        at Spec.eval (src/__tests__/DatePicker-test.js:60:48)
● DatePicker › it should change focusedDateKey on mouse down
  - Expected undefined to be defined.
        at Spec.eval (src/__tests__/DatePicker-test.js:99:45)
● DatePicker › it should reduce focusedDateKey by 1 when arrowLeft is pressed
  - TypeError: Cannot read property 'tagName' of undefined
        at Object.eval [as focus] (node_modules/react/lib/ReactTestUtils.js:381:34)
        at Spec.eval (src/__tests__/DatePicker-test.js:109:48)
● DatePicker › it should increase focusedDateKey by 1 when arrowLeft is pressed for arabic calendar
  - TypeError: Cannot read property 'tagName' of undefined
        at Object.eval [as focus] (node_modules/react/lib/ReactTestUtils.js:381:34)
        at Spec.eval (src/__tests__/DatePicker-test.js:126:48)
● DatePicker › it should reduce focusedDateKey by 7 when arrowUp is pressed
  - TypeError: Cannot read property 'tagName' of undefined
        at Object.eval [as focus] (node_modules/react/lib/ReactTestUtils.js:381:34)
        at Spec.eval (src/__tests__/DatePicker-test.js:143:48)
● DatePicker › it should increase focusedDateKey by 1 when arrowRight is pressed
  - TypeError: Cannot read property 'tagName' of undefined
        at Object.eval [as focus] (node_modules/react/lib/ReactTestUtils.js:381:34)
        at Spec.eval (src/__tests__/DatePicker-test.js:160:48)
● DatePicker › it should reduce focusedDateKey by 1 when arrowRight is pressed for arabic calendar
  - TypeError: Cannot read property 'tagName' of undefined
        at Object.eval [as focus] (node_modules/react/lib/ReactTestUtils.js:381:34)
        at Spec.eval (src/__tests__/DatePicker-test.js:177:48)
● DatePicker › it should increase focusedDateKey by 1 when arrowRight is pressed
  - TypeError: Cannot read property 'tagName' of undefined
        at Object.eval [as focus] (node_modules/react/lib/ReactTestUtils.js:381:34)
        at Spec.eval (src/__tests__/DatePicker-test.js:194:48)
● DatePicker › it should show friday as first day of week according to locale data
  - TypeError: Cannot read property '_currentElement' of undefined
        at Spec.eval (src/__tests__/DatePicker-test.js:230:70)
● DatePicker › it should change selectedDate when a day receives mouseDown with button 0
  - Expected undefined to be greater than 0.
        at Spec.eval (src/__tests__/DatePicker-test.js:245:43)
  - TypeError: Cannot read property 'getDay' of undefined
        at Spec.eval (src/__tests__/DatePicker-test.js:246:24)
● DatePicker › it should inject styles for hover, active & foucs
  - TypeError: Cannot read property 'calls' of undefined
        at Spec.eval (src/__tests__/DatePicker-test.js:289:41)
● DatePicker › it should set isWrapperHovered on mouse over for all components including disabled and readOnly
  - Expected undefined to be truthy.
        at Spec.eval (src/__tests__/DatePicker-test.js:391:47)
  - Expected undefined to be truthy.
        at Spec.eval (src/__tests__/DatePicker-test.js:400:55)
  - Expected undefined to be truthy.
        at Spec.eval (src/__tests__/DatePicker-test.js:409:55)
● DatePicker › it should focus readOnly component
  - TypeError: Cannot read property 'tagName' of undefined
        at Object.eval [as focus] (node_modules/react/lib/ReactTestUtils.js:381:34)
        at Spec.eval (src/__tests__/DatePicker-test.js:430:48)
● DatePicker › it should decrease month when prevMonthNav is clicked
  - TypeError: Cannot read property 'tagName' of undefined
        at Object.eval [as mouseDown] (node_modules/react/lib/ReactTestUtils.js:381:34)
        at Spec.eval (src/__tests__/DatePicker-test.js:440:48)
● DatePicker › it should increase month when nextMonthNav is clicked
  - TypeError: Cannot read property 'tagName' of undefined
        at Object.eval [as mouseDown] (node_modules/react/lib/ReactTestUtils.js:381:34)
        at Spec.eval (src/__tests__/DatePicker-test.js:450:48)
● DatePicker › it should apply hover styles to wrapper when mouse is over
  - Expected undefined to be truthy.
        at Spec.eval (src/__tests__/DatePicker-test.js:472:47)
  - Expected 'border-radius:2px;width:267px;font-size:14px;text-align:center;box-sizing:border-box;background-color:white;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;-ms-touch-action:manipulation;touch-action:manipulation;-webkit-tap-highlight-color:transparent;transition:color 0.1s;transition-timing-function:ease-out;' to contain 'background-color: red'.
        at Spec.eval (src/__tests__/DatePicker-test.js:473:43)
● DatePicker › it should apply activeDayStyle to day when touchStart but immediately after touchEnd should apply selectedDayStyle
  - TypeError: Cannot read property 'getDay' of undefined
        at Spec.eval (src/__tests__/DatePicker-test.js:485:41)
● DatePicker › it should not apply focusDayStyles for mouseDown wrapper
  - TypeError: Cannot read property 'tagName' of undefined
        at Object.eval [as mouseDown] (node_modules/react/lib/ReactTestUtils.js:381:34)
        at Spec.eval (src/__tests__/DatePicker-test.js:496:48)
● DatePicker › it should apply focusDayStyles for mouseDown by on day
  - TypeError: Cannot read property 'getDay' of undefined
        at Spec.eval (src/__tests__/DatePicker-test.js:509:41)
23 tests failed, 172 tests passed (195 total in 13 test suites, run time 16.825s)
```

**Comment by nikgraf** [comment]
@coopy oh damn, totally forgot to remove it. Seems like we need to fix a couple tests. Thx for pointing it out.

**Comment by magicpat** [comment]
Hey, I extended the linting config to prevent this kind of issues...
Maybe this is useful.
